import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fireEvent, render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "../routes/router";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { App } from "../App";
import { AuthProvider } from "../features/auth/AuthContext";
import type { EnhancedReport, Interpretation, MarketCoreCurrentQuotes, MarketCoreShanghai, PathMatrix, Principal, Report, Sector, SectorResearch } from "../types";

const report: Report = {
  id: "report-1", title: "虚构岛屿研究周报", report_date: "2026-07-19", candidate_report_date: "2026-07-19", report_date_confirmed: true,
  detected_report_date: "2026-07-19", report_date_source: "pdf_title", report_date_confidence: "high", report_date_confirmed_by_user: false,
  market_as_of_date: "2026-07-17", candidate_market_as_of_date: "2026-07-17", market_as_of_date_confirmed: true, enhanced_status: "ready", enhanced_revision_number: 1,
  interpretation_status: "ready",
  status: "published", core_view: "保持耐心，观察结构性机会。", market_path: "3844点以下继续防守；即使站上，也必须通过时间、市场宽度和量能验证。", risk_warning: "仅为测试。", focus_sectors: ["半导体", "恒生科技"],
  created_at: "2026-07-19T20:00:00Z", published_at: "2026-07-19T21:00:00Z", pdf_url: "/api/v1/reports/report-1/pdf", pdf_download_url: "/api/v1/reports/report-1/pdf/download", data_notice: "研究辅助数据，非生产级行情服务。",
  mentions: [{ sector_key: "semiconductor", sector_name: "半导体", summary: "关注需求验证。", extraction_status: "explicit" }], raw_text: "fixture", original_filename: "fixture.pdf", unmapped_terms: [],
};

const sectors: Sector[] = Array.from({ length: 67 }, (_, index) => ({
  sector_key: index === 64 ? "hotel" : index === 65 ? "catering" : index === 66 ? "hang_seng_tech" : `sector-${index + 1}`,
  sector_name: index === 64 ? "酒店" : index === 65 ? "餐饮" : index === 66 ? "恒生科技" : `板块${index + 1}`,
  parent_report_topic: index === 64 || index === 65 ? "hotel_catering" : index === 66 ? "hang_seng_tech" : `sector-${index + 1}`,
  report_topic_name: index === 64 || index === 65 ? "酒店餐饮" : index === 66 ? "恒生科技" : `板块${index + 1}`,
  group_name: `分组${Math.floor(index / 9) + 1}`,
  group_order: Math.floor(index / 9) + 1,
  overall_order: index + 1,
  latest_view: index === 66 ? "直播观点正常展示" : null,
  mentioned_in_latest_published: index === 66,
  market_support_status: index === 66 ? "unsupported" : "supported",
  data_status: index === 64 ? "proxy" : index === 65 ? "unverified" : index === 66 ? "unsupported" : "supported",
  market_status_detail: index === 64 ? "酒店（旅游及酒店代理口径）" : index === 65 ? "餐饮行情源待验证" : index === 66 ? "港股跨市场行情暂未接入" : "研究辅助数据",
  current_path_status: index === 66 ? "watch" : "not_mentioned",
  current_path_status_label: index === 66 ? "观察" : "未提",
  effective_status: index === 0 ? "hold" : index === 66 ? "watch" : "not_mentioned",
  effective_status_label: index === 0 ? "持有" : index === 66 ? "观察" : "未提",
  strict_holding_interval: index === 0 ? { status: "active", start_report_date: "2026-07-15", start_market_as_of_date: "2026-07-15", eod_return: 1.25, calculation_status: "complete_eod" } : null,
  broad_holding_interval: index === 0 ? { status: "active", start_report_date: "2026-07-15", start_market_as_of_date: "2026-07-15", eod_return: 2.5, calculation_status: "complete_eod" } : null,
  is_low_attention: false,
  is_pinned_for_research: false,
  recent_mention_count: index === 0 ? 3 : 0,
  attention_level: index === 0 ? "high" : "normal",
  intraday_status: index === 0 ? "intraday_fresh" : index === 66 ? "unsupported" : "provider_failed",
  intraday_snapshot: index === 0 ? { sector_key: "sector-1", trade_date: "2026-07-28", observed_at: "07/28 14:20", index_value: 101, pre_close: 100, pct_change: 1.26, volume: null, amount: null, provider: "eastmoney_board_spot", provider_role: "research_provider", data_status: "intraday_fresh", fetched_at: "2026-07-28T06:20:00Z", intraday_ma5: 99.2, intraday_vs_ma5: 1.81 } : null,
  intraday_last_attempt_at: "07/28 14:20",
  latest_market: index === 0 ? { trade_date: "2026-07-27", close: 101, pre_close: 100, daily_pct_change: 1, return_5d: 1.86, return_10d: 2, return_20d: 3, ma5: 100, ma10: 99, ma20: 98, close_vs_ma5_pct: 1.97, close_vs_ma10_pct: 2, close_vs_ma20_pct: .61, volume: 100, volume_average_5d: 90, volume_average_20d: 80, volume_ratio_5d: 1.1, volume_ratio_20d: 1.25, amount: null, history_status: "complete", eod_status: "complete_eod", data_source: "fixture", provider_role: "research_provider", fetched_at: "2026-07-27T08:00:00Z", source_response_hash: "a".repeat(64) } : null,
  timeline: index === 1 ? [{ report_id: "report-1", report_date: "2026-07-19", report_title: report.title, summary: "关注需求验证。" }] : [],
}));

const pathEntry = { id: "path-1", sector_key: "semiconductor", sector_name: "半导体", path_status: "hold" as const, path_status_label: "持有", path_status_color: "#15803d", explicitly_mentioned: true, judgement_summary: "关注需求验证。", source_text_reference: "fixture", review_status: "confirmed", manually_modified: false, revision_id: "initial" };
sectors[0].recent_path = [{ ...pathEntry, report_id: "report-1", report_date: "2026-08-05" }];
const assessment = { id: "assessment-1", sector_key: "semiconductor", sector_name: "半导体", current_path_status: "hold" as const, path_status_label: "持有", explicitly_mentioned: true, recent_path_summary: "观察转持有", current_judgement: "关注需求验证。", main_basis: "量价结构", observation_condition: "需求确认", source_section: "板块详细汇总", source_text_reference: "fixture", review_status: "confirmed", manually_modified: false, revision_id: "initial", market: null };
sectors[66].latest_view_report_id = report.id;
sectors[66].latest_view_date = report.report_date;
sectors[66].latest_explicit_view = {
  report_id: report.id,
  report_date: report.report_date!,
  path: { ...pathEntry, sector_key: "hang_seng_tech", sector_name: "恒生科技", path_status: "watch", path_status_label: "观察" },
  assessment: { ...assessment, sector_key: "hang_seng_tech", sector_name: "恒生科技", current_path_status: "watch", path_status_label: "观察", current_judgement: "直播观点正常展示" },
};
const marketCoreShanghai: MarketCoreShanghai = {
  market_core: "standalone_objective", symbol: "sh000001", name: "上证指数",
  date_axis_kind: "market_trading_day",
  live: { status: "available", current: 3856.47, pre_close: 3842.12, pct_change: .37, quote_datetime: "2026-08-11T13:42:00+08:00", server_received_at: "2026-08-11T13:42:01+08:00", freshness: "fresh", display_mode: "live", session_state: "afternoon_trading", provider: "tencent_standard_security_quote", error_code: null },
  latest_completed: { trading_date: "2026-08-08", close: 3842.12, pct_change: .31, quote_datetime: "2026-08-08T15:20:00+08:00", captured_at: "2026-08-08T15:20:01+08:00", source: "sina_public_daily_http", data_mode: "completed_eod" },
  history: [{ trading_date: "2026-08-08", close: 3842.12, pct_change: .31, quote_datetime: "2026-08-08T15:20:00+08:00", captured_at: "2026-08-08T15:20:01+08:00", source: "sina_public_daily_http", data_mode: "completed_eod" }],
  coverage: { available_days: 1, first_date: "2026-08-08", latest_date: "2026-08-08", missing_dates: [] },
  indicators: { ma5: null, ma10: null, ma20: null, distance_to_ma5_pct: null, distance_to_ma10_pct: null, distance_to_ma20_pct: null },
};
const defaultCurrentMarket: MarketCoreCurrentQuotes = {
  market_core: "standalone_objective", scope: "matrix", session_state: "afternoon_trading", provider: "tencent_standard_security_quote", cache_hit: false, provider_request_count: 1, snapshot_ttl_seconds: 60, quotes: [],
  sectors: [
    { sector_key: "sector-1", sector_name: "板块1", market_status: "available", market_session: "afternoon_trading", quote_time: "2026-08-11T14:30:15+08:00", instruments: [{ symbol: "sh515880", security_code: "515880.SH", name: "通信ETF", status: "available", current: 1.2, pre_close: 1.18, pct_change: 1.96, quote_datetime: "2026-08-11T14:30:15+08:00", server_received_at: "2026-08-11T14:30:16+08:00", freshness: "fresh", provider: "tencent_standard_security_quote", error_code: null }] },
    { sector_key: "semiconductor", sector_name: "半导体", market_status: "available", market_session: "afternoon_trading", quote_time: "2026-08-11T14:30:00+08:00", instruments: [{ symbol: "sz159995", security_code: "159995.SZ", name: "芯片ETF", status: "available", current: 1.2, pre_close: 1.1, pct_change: 9.09, quote_datetime: "2026-08-11T14:30:00+08:00", server_received_at: "2026-08-11T14:30:01+08:00", freshness: "fresh", provider: "tencent_standard_security_quote", error_code: null }] },
  ],
};
const reportDefense = { market_context_note: "报告攻防线仅来自本报告；当前或最近完整上证数据由独立市场锚点读取。", defense_line_value: 3844, defense_line_source: "core_view" as const, stand_above_condition: "即使站上，也必须通过时间、市场宽度和量能验证。", break_below_condition: "3844点以下继续防守。", validation_conditions: "即使站上，也必须通过时间、市场宽度和量能验证。", distance_points: null, distance_pct: null, defense_position: null };
const enhanced: EnhancedReport = { report, path_entries: [pathEntry], sector_assessments: [assessment], status_groups: [{ status: "hold", count: 1, items: [assessment] }], market_snapshots: [], report_defense: reportDefense, recent_defense_line_validations: [], defense_line_trend: [], intraday_defense_overlay: null, comparison: { previous_report_id: null, status_changes: [], counts: {} }, market_data_attached: false, data_notice: report.data_notice };
const enhancedWithShanghaiAnchor: EnhancedReport = {
  ...enhanced,
  market_data_attached: true,
};
const interpretation: Interpretation = {
  report_id: report.id, status: "ready", report_date: report.report_date, detected_report_date: report.detected_report_date,
  report_date_source: "pdf_title", report_date_confidence: "high", report_date_confirmed_by_user: false,
  candidate_market_as_of_date: report.candidate_market_as_of_date, market_as_of_date: null, market_data_status: "not_bound",
  field_provenance: {}, attention_items: [], mapping_summary: { confirmed: 1, probable: 0, unmapped: 0, conflict: 0 },
  status_counts: { avoid: 0, strong_watch: 0, watch: 0, weak_watch: 0, turn_hold: 0, hold: 1, turn_weak: 0, exit: 0, not_mentioned: 65 },
  mentioned_assessments: [assessment], relevant_path_entries: [pathEntry], all_path_entries: [{ ...pathEntry, group_name: "科技硬件与通信" }],
  path_entry_count: 66, external_llm_calls: 0, ocr_used: false,
  quality_status: "verified_structure", quality_summary: { report_structure: "verified_structure", history_matrix: "verified_structure", history_rows: 66, assessment_rows: 1, assessment_verified: 1, assessment_blocking: 0 }, pdf_history_matrix: { dates: [], rows: [] },
  review_workflow: { workflow_status: "ready_to_publish", summary: { auto_confirmed: 66, suggested_review: 0, must_handle: 0, handled: 0 }, steps: [{ key: "upload", label: "上传报告", state: "complete" }, { key: "review", label: "检查疑问", state: "complete" }, { key: "publish", label: "发布报告", state: "current" }], issues: [] },
};
const matrix: PathMatrix = { caption: "板块历史路径矩阵", dates: [{ trading_date: "2026-07-17", weekday: "周五" }], groups: [{ group_order: 1, group_name: "科技硬件与通信", sector_count: 1 }], rows: [{ sector_key: "semiconductor", sector_name: "半导体", group_name: "科技硬件与通信", group_order: 1, overall_order: 1, cells: [{ ...pathEntry, trading_date: "2026-07-17", report_present: true, report_id: report.id, detail_report_id: report.id, has_detailed_report: true, report_date: report.report_date! }] }], status_contract: { statuses: [{ code: "hold", label: "持有", color: "#15803d", order: 1 }] } };
const sectorTradingDates = ["2026-07-20", "2026-07-21", "2026-07-22", "2026-07-23", "2026-07-24", "2026-07-27", "2026-07-28", "2026-07-29", "2026-07-30", "2026-07-31"];
const sectorRecentDays = sectorTradingDates.map((trading_date, index) => ({ trading_date, daily_pct_change: index === 0 ? 1 : index === 1 ? -1 : index === 2 ? 0 : .5, close: 100 + index }));
const primaryMarket = { symbol: "sh515880", security_code: "515880.SH", name: "通信ETF", role: "etf" as const, date_axis_kind: "market_trading_day" as const, trade_date: "2026-07-31", close: 109, daily_pct_change: .5, return_10d: 2, history_days: 10, history: sectorRecentDays, ma5: 107, ma10: 104.5, ma20: null, close_vs_ma5_pct: 1.87, close_vs_ma10_pct: 4.31, close_vs_ma20_pct: null };
sectors[0].primary_market = primaryMarket;
const research: SectorResearch = { sector_key: "sector-2", sector_name: "板块2", group_name: "分组1", latest_explicit_view: { report_id: report.id, report_date: report.report_date!, path: pathEntry, assessment, report_snapshot: null }, latest_report_date: "2026-08-11", latest_report_explicitly_mentioned: false, current_latest_market: sectors[0].latest_market, primary_market: primaryMarket, recent_10_trading_days: sectorRecentDays, market_support_status: "supported", data_status: "supported", market_status_detail: "研究辅助数据", history: [{ report_id: report.id, report_date: report.report_date!, path: pathEntry, assessment, report_snapshot: null }] };

function response(payload: unknown, status = 200) { return Promise.resolve(new Response(status === 204 ? null : JSON.stringify(payload), { status, headers: { "Content-Type": "application/json" } })); }
const websiteMdFixture = `---
schema: leopard-website-md
schema_version: "1.0"
report_date: "2026-09-01"
display_row_count: 74
active_object_count: 71
---
## 4. 当日板块更新
\`\`\`yaml
sector_updates:
${Array.from({ length: 16 }, (_, index) => `  - sector: "更新${index + 1}"`).join("\n")}
\`\`\`
## 5. 本场未更新板块
\`\`\`yaml
unmentioned_sectors:
${Array.from({ length: 55 }, (_, index) => `  - "未提${index + 1}"`).join("\n")}
\`\`\``;
function mockApi(options: { empty?: boolean; duplicate?: boolean; enhancedReport?: EnhancedReport; sectorResearch?: SectorResearch; pathMatrix?: PathMatrix; currentMarket?: MarketCoreCurrentQuotes; sectors?: Sector[]; viewerObservation?: unknown } = {}) {
  vi.stubGlobal("fetch", vi.fn((input: RequestInfo | URL) => {
    const url = String(input);
    if (url.endsWith("/reports/latest")) return options.empty ? response({ error: { code: "no_published_report", message: "none" } }, 404) : response(report);
    if (url.endsWith("/reports/report-1/enhanced")) return response(options.enhancedReport ?? enhanced);
    if (url.endsWith("/market/shanghai")) return response(marketCoreShanghai);
    if (url.endsWith("/market/current/matrix")) return response(options.currentMarket ?? defaultCurrentMarket);
    if (url.endsWith("/reports/report-1/pdf/preview")) return response({ page_count: 2, page_urls: ["/preview/1", "/preview/2"], render_mode: "server_memory_png" });
    if (url.includes("/reports/report-1/path-matrix")) return response(options.pathMatrix ?? matrix);
    if (url.endsWith("/reports") && !url.includes("admin")) return response(options.empty ? [] : [report]);
    if (url.includes("/reports/report-1") && !url.includes("admin")) return response(report);
    if (url.includes("/sectors?")) return response(options.sectors ?? sectors);
    if (url.endsWith("/auth/me")) return response({ username: "viewer", role: "viewer" });
    if (url.endsWith("/market/intraday/status")) return response({ session_status: "running", market_phase: "intraday_open", market_phase_detail: "intraday_open", intraday_trade_date: "2026-07-28", refresh_interval_minutes: 5, provider: "eastmoney_board_spot", provider_role: "research_provider", production_primary: null, production_primary_approved: false, research_notice: "研究辅助数据", last_refresh_at: "07/28 14:20", last_attempt_at: "07/28 14:20", next_refresh_at: "07/28 14:25", latest_snapshot_at: "07/28 14:20", success_count: 8, failure_count: 58, stale_count: 0, supported_market_path_count: 66, unsupported_count: 1, viewer_provider_access: false, auto_start: true });
    if (url.includes("/market-paths/") && url.endsWith("/viewer-observation")) return response(options.viewerObservation ?? { market_path_key: "sector-2", viewer_source_mode: "unavailable", fallback_reason: "provider_failed", official_board: { available: false, fresh: false }, security_proxy: null, disclosure: null });
    if (url.includes("/sectors/sector-2/research")) return response(options.sectorResearch ?? research);
    if (url.includes("/sectors/semiconductor/research")) return response({ ...research, sector_key: "semiconductor", sector_name: "半导体" });
    if (url.includes("/sectors/sector-2")) return response(sectors[1]);
    if (url.endsWith("/admin/summary")) return response({ drafts: 1, needs_review: 1, published: 1, parse_failed: 0, unmapped_terms: 0 });
    if (url.endsWith("/admin/operations/status")) return response({ build_commit: "test-build", data_snapshot_date: "2026-08-11", latest_published_report_date: "2026-08-11", latest_live_market_anchor_eod_date: "2026-08-11", latest_security_proxy_eod_date: "2026-08-11", capture_mode: "host_systemd_timer", capture_schedule: "Mon-Fri 15:20 Asia/Shanghai; controlled calendar may skip" });
    if (url.includes("/admin/report-days?")) return response([]);
    if (url.endsWith("/admin/reports/interpret")) return response({ report, interpretation, duplicate: options.duplicate ?? false, publication: options.duplicate ? "already_published" : "needs_review", interpretation_error: null, processing_steps: [] }, 201);
    if (url.endsWith("/admin/reports/report-1/interpretation")) return response({ report, interpretation });
    if (url.endsWith("/admin/reports") && !url.includes("report-1")) return response({ report: report, interpretation, duplicate: options.duplicate ?? false }, 201);
    if (url.includes("/admin/reports/report-1")) return response({ ...report, status: "needs_review" });
    return response({ error: { code: "not_found", message: "not found" } }, 404);
  }));
}
function renderAt(path: string, principal: Principal | null = { username: "viewer", role: "viewer" }) { return render(<MemoryRouter initialEntries={[path]}><AuthProvider initialPrincipal={principal}><App /></AuthProvider></MemoryRouter>); }

describe("Viewer research pages", () => {
  beforeEach(() => mockApi());
  it("shows a friendly empty home state", async () => { mockApi({ empty: true }); renderAt("/"); expect(await screen.findByText("暂无已发布报告。")).toBeInTheDocument(); });
  it("shows report-fact core characterization and execution before defense validation", async () => { renderAt("/"); expect(await screen.findByRole("heading", { name: report.title })).toBeInTheDocument(); expect(screen.getByText(report.core_view)).toBeInTheDocument(); expect(screen.getByText("核心定性")).toBeInTheDocument(); expect(screen.getByText("执行结论")).toBeInTheDocument(); expect(screen.getByText("客观市场锚点")).toBeInTheDocument(); expect(screen.getByText("000001.SH")).toBeInTheDocument(); expect(screen.getByText("盘中 13:42")).toBeInTheDocument(); expect(screen.getByText("最近完整收盘")).toBeInTheDocument(); expect(screen.getByText("宽基市场观察暂不可用。")).toBeInTheDocument(); expect(screen.getAllByText("3,844.00")).toHaveLength(1); expect(screen.queryByText(/3,844\.00 点/)).not.toBeInTheDocument(); expect(screen.getByText("攻防线上方")).toHaveClass("a-share-positive"); expect(screen.getByText(/核心判断安全回退/)).toBeInTheDocument(); const panel = document.querySelector(".core-insight-panel"); const parts = Array.from(panel?.children ?? []).map(item => item.textContent ?? ""); expect(parts.findIndex(item => item.includes("执行结论"))).toBeLessThan(parts.findIndex(item => item.includes("近10个交易日猎豹攻防点"))); expect(document.body).not.toHaveTextContent("tencent_standard_security_quote"); expect(document.body).not.toHaveTextContent("sina_public_daily_http"); });
  it("shows only descriptive recent defense validations and a completed-day distance trend", async () => { mockApi({ enhancedReport: { ...enhancedWithShanghaiAnchor, recent_defense_line_validations: [{ trading_date: "2026-08-11", source_report_id: "prior", source_report_date: "2026-08-10", defense_line_value: 3844, index_name: "上证指数", index_close: 3851, distance_points: 7, distance_pct: .18, close_position: "close_above_defense_line" }], defense_line_trend: [{ trading_date: "2026-08-10", available: true, source_report_id: "prior", source_report_date: "2026-08-09", defense_line_value: 3844, index_name: "上证指数", index_close: 3851, distance_points: 7, distance_pct: .18, close_position: "close_above_defense_line", data_mode: "completed_eod" }] } }); renderAt("/"); expect(await screen.findByText("近10个交易日猎豹攻防点")).toBeInTheDocument(); expect(screen.getByText("来自 08-10 报告")).toBeInTheDocument(); expect(screen.getByText("收盘在线上")).toHaveClass("a-share-positive"); expect(screen.getByText("+7.00")).toHaveClass("a-share-positive"); expect(screen.getByText("当前已积累 1 / 10 条完整验证记录。")).toBeInTheDocument(); expect(screen.getByText("近30个交易日攻防距离趋势")).toBeInTheDocument(); expect(screen.getByText("点数")).toBeInTheDocument(); const bar = screen.getByTestId("defense-distance-bar-2026-08-10"); expect(bar).toHaveClass("defense-distance-bar-positive"); fireEvent.mouseEnter(bar); expect(screen.getByRole("tooltip")).toHaveTextContent("距攻防线：+7.00 点"); expect(screen.getByRole("tooltip")).toHaveTextContent("百分比差：+0.18%"); expect(screen.getByTestId("defense-distance-chart")).toBeInTheDocument(); expect(screen.getByText(/不构成预测评分/)).toBeInTheDocument(); expect(screen.queryByText(/成功率|有效率/)).not.toBeInTheDocument(); });
  it("keeps ten completed defense rows separate from a view-only intraday overlay", async () => { mockApi({ enhancedReport: { ...enhancedWithShanghaiAnchor, recent_defense_line_validations: [{ trading_date: "2026-08-20", source_report_id: "prior", source_report_date: "2026-08-19", defense_line_value: 3844, index_name: "上证指数", index_close: 3851, distance_points: 7, distance_pct: .18, close_position: "close_above_defense_line" }], defense_line_trend: [{ trading_date: "2026-08-20", available: true, source_report_id: "prior", source_report_date: "2026-08-19", defense_line_value: 3844, index_name: "上证指数", index_close: 3851, distance_points: 7, distance_pct: .18, close_position: "close_above_defense_line", data_mode: "completed_eod" }], intraday_defense_overlay: { available: true, data_mode: "intraday_overlay", trading_date: "2026-08-21", quote_datetime: "2026-08-21T13:30:00+08:00", session_state: "afternoon_trading", source_report_id: "today-source", source_report_date: "2026-08-20", defense_line_value: 3844, index_name: "上证指数", index_current: 3854, distance_points: 10, distance_pct: .26, close_position: "close_above_defense_line" } } }); renderAt("/"); expect(await screen.findByText(/08-21 · 盘中/)).toBeInTheDocument(); const intradayBar = screen.getByTestId("defense-distance-bar-2026-08-21-intraday"); expect(intradayBar).toHaveClass("defense-distance-bar-intraday"); expect(document.querySelectorAll(".defense-validation-row:not(.defense-validation-header)")).toHaveLength(2); expect(screen.getByText("当前已积累 1 / 10 条完整验证记录。")).toBeInTheDocument(); });
  it("uses defined A-share fills for positive and negative defense bars", () => { const tokens = readFileSync(resolve(process.cwd(), "src/styles/tokens.css"), "utf8"); const css = readFileSync(resolve(process.cwd(), "src/styles/global.css"), "utf8"); expect(tokens).toMatch(/--a-share-red:\s*#c53535/); expect(tokens).toMatch(/--a-share-green:\s*#177245/); expect(css).toMatch(/\.defense-distance-bar-positive\s*\{\s*fill:\s*var\(--a-share-red\)/); expect(css).toMatch(/\.defense-distance-bar-negative\s*\{\s*fill:\s*var\(--a-share-green\)/); });
  it("keeps a compact defense table and truthful zero-record state while moving risk below the main content", async () => { renderAt("/"); expect(await screen.findByText("攻防验证记录将随交易日自然积累。")).toBeInTheDocument(); expect(screen.getByText("当前已积累 0 / 10 条完整验证记录。")).toBeInTheDocument(); expect(screen.getByRole("table", { name: "攻防验证明细" })).toHaveTextContent("交易日"); const overview = document.querySelector(".report-overview-grid"); expect(overview?.children).toHaveLength(2); expect(overview?.children[0]).toHaveTextContent("近10个交易日猎豹攻防点"); expect(overview?.children[1]).toHaveTextContent("风险提示"); const css = readFileSync(resolve(process.cwd(), "src/styles/global.css"), "utf8"); expect(css).toMatch(/\.report-overview-grid\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)/); expect(css).toMatch(/\.proxy-recent-closes\s*\{[^}]*repeat\(5/); expect(css).toMatch(/@media \(max-width: 760px\)[\s\S]*\.proxy-recent-closes\s*\{[^}]*repeat\(2/); });
  it("keeps the market overview vertical before the broad ETF cards and table", async () => { renderAt("/"); await screen.findByText("上证指数"); const core = document.querySelector(".core-insight-panel"); const text = Array.from(core?.children ?? []).map(item => item.textContent ?? ""); expect(text.findIndex(item => item.includes("上证指数"))).toBeLessThan(text.findIndex(item => item.includes("猎豹攻防点"))); const css = readFileSync(resolve(process.cwd(), "src/styles/global.css"), "utf8"); expect(css).toMatch(/core-insight-panel\s*\{[^}]*grid-template-areas:\s*"judgment"\s*"market"\s*"defense"\s*"validation"\s*"broad"/); expect(css).toMatch(/\.aligned-broad-market-table\s*\{[^}]*width:\s*100%/); });
  it("renders available defense rows newest first and keeps all rows below the ten-record cap", async () => { const rows = Array.from({ length: 3 }, (_, index) => ({ trading_date: `2026-08-${String(11 - index).padStart(2, "0")}`, source_report_id: `prior-${index}`, source_report_date: `2026-08-${String(10 - index).padStart(2, "0")}`, defense_line_value: 3844, index_name: "上证指数", index_close: 3851 - index, distance_points: 7 - index * 7, distance_pct: .18 - index * .18, close_position: index === 0 ? "close_above_defense_line" as const : index === 1 ? "close_at_defense_line" as const : "close_below_defense_line" as const })); mockApi({ enhancedReport: { ...enhancedWithShanghaiAnchor, recent_defense_line_validations: rows } }); renderAt("/"); expect(await screen.findByText("当前已积累 3 / 10 条完整验证记录。")).toBeInTheDocument(); const renderedRows = Array.from(document.querySelectorAll(".defense-validation-row:not(.defense-validation-header)")); expect(renderedRows).toHaveLength(3); expect(renderedRows[0]).toHaveTextContent("08-11"); expect(renderedRows[1]).toHaveTextContent("08-10"); expect(renderedRows[2]).toHaveTextContent("08-09"); expect(screen.getByText("收盘与线相等")).toHaveClass("a-share-neutral"); expect(screen.getByText("收盘在线下")).toHaveClass("a-share-negative"); });
  it("identifies the defense level as belonging to the rendered report date", async () => { renderAt("/"); await screen.findByText("猎豹攻防点"); expect(screen.getByText(`来自 ${report.report_date} 报告`)).toBeInTheDocument(); });
  it("keeps moving averages readable when the current index quote is stale", async () => { mockApi(); vi.stubGlobal("fetch", vi.fn((input: RequestInfo | URL) => String(input).endsWith("/market/shanghai") ? response({ ...marketCoreShanghai, live: { ...marketCoreShanghai.live, status: "unavailable", current: null, pre_close: null, pct_change: null, quote_datetime: null, freshness: "stale", error_code: "stale_quote" }, indicators: { ma5: 3840.5, ma10: 3830.5, ma20: 3820.5, distance_to_ma5_pct: null, distance_to_ma10_pct: null, distance_to_ma20_pct: null } }) : String(input).endsWith("/reports/latest") ? response(report) : String(input).endsWith("/reports/report-1/enhanced") ? response(enhancedWithShanghaiAnchor) : String(input).includes("/path-matrix") ? response(matrix) : response({ error: { code: "not_found", message: "not found" } }, 404))); renderAt("/"); expect(await screen.findByText(/当前实时行情已结束/)).toBeInTheDocument(); expect(screen.getByText("3,840.50")).toBeInTheDocument(); expect(screen.getAllByText("2026-08-08")).toHaveLength(1); expect(screen.getByText("3,844.00")).toBeInTheDocument(); expect(screen.queryByText("0.00%")).not.toBeInTheDocument(); });
  it("shows the report list without weekend missing warnings", async () => { renderAt("/reports"); expect(await screen.findByRole("table", { name: "已发布报告" })).toBeInTheDocument(); expect(screen.getByText(/周五、周六无报告属于正常节奏/)).toBeInTheDocument(); });
  it("shows report details without requesting PDF or preview pages until requested", async () => { const user = userEvent.setup(); renderAt("/reports/report-1"); expect(await screen.findByRole("heading", { level: 1, name: report.title })).toBeInTheDocument(); expect(screen.getByRole("table", { name: /板块历史路径矩阵/ })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "最近20个交易日" })).toHaveClass("active"); expect(screen.queryByLabelText("原始PDF逐页预览")).not.toBeInTheDocument(); expect(screen.getByRole("link", { name: "下载原始PDF" })).toHaveAttribute("href", report.pdf_download_url); expect(fetch).not.toHaveBeenCalledWith(expect.stringContaining("/pdf/preview"), expect.anything()); await user.click(screen.getByRole("button", { name: "加载逐页预览" })); expect(await screen.findByLabelText("原始PDF逐页预览")).toBeInTheDocument(); expect(screen.getByAltText("原始PDF第1页")).toHaveAttribute("src", "/preview/1"); });
  it("renders the report-object catalog in eight fixed groups", async () => { renderAt("/sectors"); const table = await screen.findByRole("table", { name: /板块研究档案/ }); expect(within(table).getAllByRole("row")).toHaveLength(76); expect(table).toHaveTextContent("当前67个显示对象；71个active Report Object"); expect(screen.getByRole("navigation", { name: "板块研究一级分组快捷导航" }).querySelectorAll("button")).toHaveLength(8); });
  it("keeps the public sector catalog when an anonymous auth probe returns 401", async () => { const normalFetch = globalThis.fetch; vi.stubGlobal("fetch", vi.fn((input: RequestInfo | URL) => String(input).endsWith("/auth/me") ? response({ error: { code: "authentication_required", message: "anonymous" } }, 401) : normalFetch(input))); renderAt("/sectors", null); const table = await screen.findByRole("table", { name: /板块研究档案/ }); expect(within(table).getAllByRole("row")).toHaveLength(76); expect(screen.getByText("实时行情 8/66")).toBeInTheDocument(); });
  it("board_current_and_10day_same_primary with same-primary MA fields", async () => { renderAt("/sectors"); const table = await screen.findByRole("table", { name: /板块研究档案/ }); expect(screen.getByText("实时行情 8/66")).toBeInTheDocument(); expect(screen.getByText("暂无数据58项")).toBeInTheDocument(); expect(within(table).getByRole("columnheader", { name: "当前/最近行情" })).toBeInTheDocument(); expect(within(table).getByText("通信ETF")).toBeInTheDocument(); expect(within(table).getByText("515880.SH")).toBeInTheDocument(); expect(within(table).getByText((_, element) => element?.tagName === "SMALL" && element.textContent === "现价 1.200")).toBeInTheDocument(); expect(within(table).getByText("今日 +1.96%")).toBeInTheDocument(); expect(within(table).getByText("行情时间 14:30:15")).toBeInTheDocument(); expect(within(table).getByText("+2.00%")).toBeInTheDocument(); expect(within(table).getByText("MA5 ↑1.87%")).toBeInTheDocument(); expect(within(table).queryByText("代理口径")).not.toBeInTheDocument(); expect(table).not.toHaveTextContent("2026-07-28T"); });
  it("keeps representative identity and truthful unavailable copy when current quotes fail", async () => { mockApi({ currentMarket: { market_core: "standalone_objective", scope: "matrix", session_state: "afternoon_trading", provider: "tencent_standard_security_quote", cache_hit: false, provider_request_count: 1, quotes: [], sectors: [] } }); renderAt("/sectors"); const table = await screen.findByRole("table", { name: /板块研究档案/ }); expect(within(table).getByText("通信ETF")).toBeInTheDocument(); expect(within(table).getByText("515880.SH")).toBeInTheDocument(); expect(within(table).getAllByText("行情暂不可用").length).toBeGreaterThan(0); expect(table).not.toHaveTextContent("现价 0"); });
  it("keeps every server-provided report object distinct in the public catalog", async () => { renderAt("/sectors"); expect(await screen.findByRole("link", { name: "酒店" })).toHaveAttribute("href", "/sectors/hotel"); expect(screen.getByRole("link", { name: "餐饮" })).toHaveAttribute("href", "/sectors/catering"); });
  it("dormant_toggle_behavior_unchanged", async () => { const dormant = sectors.map((item, index) => ({ ...item, is_dormant_20d: index === 1, dormant_report_overlay_count: index === 1 ? 12 : 0 })); mockApi({ sectors: dormant }); const user = userEvent.setup(); renderAt("/sectors"); await screen.findByRole("table", { name: /板块研究档案/ }); expect(screen.queryByRole("link", { name: "板块2" })).not.toBeInTheDocument(); await user.type(screen.getByLabelText("搜索"), "板块2"); expect(screen.getByRole("link", { name: "板块2" })).toBeInTheDocument(); await user.clear(screen.getByLabelText("搜索")); await user.click(screen.getByLabelText(/显示20日未提板块/)); expect(screen.getByRole("link", { name: "板块2" })).toBeInTheDocument(); });
  it("dormant_checkbox_uses_compact_size", async () => { renderAt("/reports/report-1"); await screen.findByRole("table", { name: /板块历史路径矩阵/ }); const checkbox = screen.getByLabelText(/显示20日未提板块/); expect(checkbox).toHaveAttribute("type", "checkbox"); const css = readFileSync(resolve(process.cwd(), "src/styles/global.css"), "utf8"); expect(css).toMatch(/\.matrix-controls \.matrix-dormant-toggle input\[type="checkbox"\][^}]*width:\s*17px[^}]*height:\s*17px/); expect(css).toMatch(/\.matrix-controls input:not\(\[type="checkbox"\]\)/); });
  it("separates HSTECH opinion and unsupported market status", async () => { renderAt("/sectors"); expect(await screen.findByTitle(/直播观点正常展示/)).toBeInTheDocument(); expect(screen.getByText("不支持1项")).toBeInTheDocument(); });
  it("shows report-timeline strict and broad holding ranges", async () => { renderAt("/sectors"); expect(await screen.findByText("绝对 07/15 → 至今")).toBeInTheDocument(); expect(screen.getByText("广义 07/15 → 至今")).toBeInTheDocument(); });
  it("keeps ten-day details collapsed and an accessible holding explanation", async () => { const user = userEvent.setup(); renderAt("/sectors"); await screen.findByText("通信ETF"); const detail = document.querySelector<HTMLDetailsElement>(".primary-ten-detail"); expect(detail).not.toBeNull(); expect(detail).not.toHaveAttribute("open"); expect(screen.getByText("收盘 100.00")).not.toBeVisible(); await user.click(detail!.querySelector("summary")!); expect(screen.getByText("收盘 100.00")).toBeVisible(); expect(screen.getByText(/只连续计算“转持、持有”/)).toBeVisible(); const summary = screen.getByText("查看详细定义"); await user.click(summary); expect(summary.parentElement).toHaveAttribute("open"); });
  it("uses shared matrix columns and bottom-aligned empty cells without changing the time axis", async () => { renderAt("/reports/report-1"); const table = await screen.findByRole("table", { name: /板块历史路径矩阵/ }); const headers = Array.from(table.querySelectorAll("thead th")).map(item => item.textContent ?? ""); expect(headers.some(item => item.includes("7/17") && item.includes("五") && !item.includes("报") && !item.includes("行"))).toBe(true); expect(screen.getByRole("navigation", { name: "一级分组快捷导航" })).toBeInTheDocument(); expect(table).toHaveAttribute("data-column-model", "fixed"); expect(table.querySelector(".matrix-group-label.sticky-sector")).toHaveTextContent("科技硬件与通信"); expect(table.querySelector("col.matrix-date-column")).not.toBeNull(); expect(table.querySelector(".matrix-current-heading")).toHaveTextContent("当前行情"); expect(await screen.findByText("芯片ETF")).toBeInTheDocument(); const css = readFileSync(resolve(process.cwd(), "src/styles/global.css"), "utf8"); expect(css).toMatch(/\.matrix-date-column\s*\{\s*width:\s*var\(--matrix-date-column\)/); expect(css).toMatch(/\.sticky-current\s*\{[^}]*position:\s*sticky/); expect(css).toMatch(/\.path-cell\s*\{[^}]*grid-template-rows:/); });
  it("keeps a market-only trading day neutral and distinguishes it in the detail dialog", async () => { const marketOnly: PathMatrix = { ...matrix, dates: [{ trading_date: "2026-07-16", weekday: "周四" }, ...matrix.dates], rows: [{ ...matrix.rows[0], cells: [{ ...matrix.rows[0].cells[0], id: "market-semiconductor-2026-07-16", trading_date: "2026-07-16", report_present: false, report_id: null, detail_report_id: null, has_detailed_report: false, report_date: null, path_status: null, path_status_label: null, path_status_color: null, revision_id: null }, ...matrix.rows[0].cells] }] }; mockApi({ pathMatrix: marketOnly }); const user = userEvent.setup(); renderAt("/reports/report-1"); const cell = await screen.findByRole("button", { name: /半导体 行情 2026-07-16 该交易日无对应报告观点/ }); expect(cell.querySelector(".matrix-report-layer")).toHaveClass("path-no-report"); expect(cell.querySelector(".matrix-market-layer")).toHaveTextContent("—"); await user.click(cell); expect(await screen.findByText("该交易日无对应报告观点。")).toBeInTheDocument(); expect(screen.getByRole("dialog")).toHaveTextContent("行情 2026-07-16"); });
  it("places the group report-date axis in the same recent-ten-periods column as row chips", async () => { renderAt("/sectors"); expect(await screen.findByText("08/05")).toBeInTheDocument(); const strip = document.querySelector(".mini-path-strip i"); expect(strip).toHaveTextContent("持"); expect(strip).not.toHaveTextContent("08/05"); const axisCell = document.querySelector(".sector-group-row .group-recent10-axis"); expect(axisCell).toHaveTextContent("08/05"); expect(axisCell?.parentElement?.querySelector("th")).not.toHaveTextContent("08/05"); });
  it("shows one stable primary in a two-line market layer without a synthetic return", async () => { const pathMatrix: PathMatrix = { ...matrix, rows: [{ ...matrix.rows[0], cells: [{ ...matrix.rows[0].cells[0], market_overlay: { kind: "primary", label: "通信ETF +1.10%", market_date: "2026-08-10", pct_change: 1.1, primary: { name: "通信ETF", security_code: "515880.SH", role: "etf", close: 1.25, pct_change: 1.1, trading_date: "2026-08-10" }, instruments: [{ name: "中际旭创", security_code: "300308.SZ", role: "leader", close: 100, pct_change: -0.5, trading_date: "2026-08-10" }] } }] }] }; mockApi({ pathMatrix }); const user = userEvent.setup(); renderAt("/reports/report-1"); await screen.findByRole("button", { name: /半导体.*通信ETF/ }); const marketLayer = document.querySelector<HTMLElement>(".matrix-desktop .matrix-market-layer"); expect(marketLayer?.querySelector("small")).toHaveClass("matrix-market-name"); expect(marketLayer).toHaveTextContent("通信ETF"); expect(marketLayer?.querySelector("em")).toHaveClass("matrix-market-pct", "a-share-positive"); const css = readFileSync(resolve(process.cwd(), "src/styles/global.css"), "utf8"); expect(css).toMatch(/\.matrix-market-layer\s*\{[^}]*display:\s*grid[^}]*grid-template-rows:\s*auto auto/); expect(css).toMatch(/\.matrix-market-name\s*\{[^}]*font-size:\s*inherit[^}]*font-weight:\s*600[^}]*text-overflow:\s*ellipsis/); expect(css).toMatch(/\.matrix-market-pct\s*\{[^}]*font-size:\s*\.84rem[^}]*font-weight:\s*700/); expect(screen.queryByText(/代理 \d|官方 \+/)).not.toBeInTheDocument(); await user.click(screen.getByRole("button", { name: /半导体.*通信ETF/ })); expect(await screen.findByText("主观察标的")).toBeInTheDocument(); expect(screen.getByText("通信ETF · 515880.SH")).toBeInTheDocument(); expect(screen.getByText("以下为相关证券逐项表现，不代表板块指数或综合收益。")).toBeInTheDocument(); expect(screen.queryByText(/平均收益|加权收益|合成指数/)).not.toBeInTheDocument(); });
  it("matrix_current_market_security_code_visible", async () => { renderAt("/reports/report-1"); const current = await screen.findByText("芯片ETF", { selector: ".matrix-current-security-top b" }); const cell = current.closest(".matrix-current-cell"); expect(cell).toHaveTextContent("159995.SZ"); expect(cell?.querySelector(".matrix-current-security-code")).toHaveTextContent("159995.SZ"); expect(cell?.querySelector("em")).toHaveClass("a-share-positive"); });
  it("matrix_current_multi_security_codes_visible_and_historical_cells_do_not_add_codes", async () => { const cpoMatrix: PathMatrix = { ...matrix, rows: [{ ...matrix.rows[0], sector_key: "cpo", sector_name: "CPO", cells: [{ ...matrix.rows[0].cells[0], sector_key: "cpo", sector_name: "CPO", market_overlay: { kind: "primary", label: "通信ETF +1.10%", market_date: "2026-08-10", pct_change: 1.1, primary: { name: "通信ETF", security_code: "515880.SH", role: "etf", close: 1.25, pct_change: 1.1, trading_date: "2026-08-10" }, instruments: [] } }] }] }; const currentMarket: MarketCoreCurrentQuotes = { market_core: "standalone_objective", scope: "matrix", session_state: "afternoon_trading", provider: "tencent_standard_security_quote", cache_hit: false, provider_request_count: 1, snapshot_ttl_seconds: 60, quotes: [], sectors: [{ sector_key: "cpo", sector_name: "CPO", market_status: "available", market_session: "afternoon_trading", quote_time: "2026-08-11T14:30:00+08:00", instruments: [{ symbol: "sh515880", security_code: "515880.SH", name: "通信ETF", status: "available", current: 1.2, pre_close: 1.1, pct_change: 1.96, quote_datetime: "2026-08-11T14:30:00+08:00", server_received_at: "2026-08-11T14:30:01+08:00", freshness: "fresh", provider: "tencent_standard_security_quote", error_code: null }, { symbol: "sz300308", security_code: "300308.SZ", name: "中际旭创", status: "available", current: 100, pre_close: 96, pct_change: 4.17, quote_datetime: "2026-08-11T14:30:00+08:00", server_received_at: "2026-08-11T14:30:01+08:00", freshness: "fresh", provider: "tencent_standard_security_quote", error_code: null }] }] }; mockApi({ pathMatrix: cpoMatrix, currentMarket }); renderAt("/reports/report-1"); await screen.findByText("通信ETF", { selector: ".matrix-current-security-top b" }); expect(document.querySelectorAll(".matrix-current-security-code")).toHaveLength(2); expect(screen.getByText("515880.SH", { selector: ".matrix-current-security-code" })).toBeInTheDocument(); expect(screen.getByText("300308.SZ", { selector: ".matrix-current-security-code" })).toBeInTheDocument(); const historicalLayer = document.querySelector<HTMLElement>(".matrix-market-layer"); expect(historicalLayer).toHaveTextContent("通信ETF"); expect(historicalLayer?.querySelector(".matrix-current-security-code")).toBeNull(); expect(historicalLayer).not.toHaveTextContent("515880.SH"); });
  it("shows a sector opinion timeline", async () => { renderAt("/sectors/sector-2"); expect(await screen.findAllByText("关注需求验证。")).not.toHaveLength(0); expect(screen.getByText("本期报告（2026-08-11）未提及；沿用最近明确观点。")).toBeInTheDocument(); });
  it("shows the timeline market basis once and omits a duplicate same-day market date", async () => { const timelineResearch: SectorResearch = { ...research, timeline_market_basis: { name: "通信ETF", security_code: "515880.SH" }, recent_path: [{ id: "timeline-1", report_id: "report-1", detail_report_id: "report-1", report_date: "2026-08-05", market_as_of_date: "2026-08-05", reported_status: "hold", effective_status: "hold", has_detailed_assessment: true, path: pathEntry, market_overlay: { kind: "primary", label: "通信ETF +1.10%", market_date: "2026-08-05", pct_change: 1.1, primary: { name: "通信ETF", security_code: "515880.SH", role: "etf", close: 1.25, pct_change: 1.1, trading_date: "2026-08-05" }, instruments: [{ name: "中际旭创", security_code: "300308.SZ", role: "leader", close: 100, pct_change: -0.5, trading_date: "2026-08-05" }] } }] }; mockApi({ sectorResearch: timelineResearch }); const user = userEvent.setup(); renderAt("/sectors/sector-2"); const basis = await screen.findByText("通信ETF · 515880.SH", { selector: ".sector-timeline-market-basis strong" }); expect(basis).toBeInTheDocument(); expect(document.querySelectorAll(".sector-timeline-market-basis strong")).toHaveLength(1); const tile = await screen.findByRole("button", { name: /08-05.*持.*\+1.10%/ }); expect(tile.querySelector(".sector-timeline-report")).toHaveClass("path-hold"); expect(tile.querySelector(".sector-timeline-market em")).toHaveClass("a-share-positive"); expect(tile.querySelector(".sector-timeline-market small")).toBeNull(); await user.click(tile); const detail = screen.getByLabelText("路径与行情详情"); expect(detail).toHaveTextContent("路径与行情详情 · 2026-08-05"); expect(within(detail).getByText("通信ETF · 515880.SH")).toBeInTheDocument(); expect(within(detail).getByText("中际旭创 · 300308.SZ")).toBeInTheDocument(); expect(within(detail).getByText(/不代表板块指数或综合收益/)).toBeInTheDocument(); expect(screen.queryByText(/平均收益|加权收益/)).not.toBeInTheDocument(); });
  it("makes a mapped weekend market date explicit in the timeline tile", async () => { const timelineResearch: SectorResearch = { ...research, timeline_market_basis: { name: "通信ETF", security_code: "515880.SH" }, recent_path: [{ id: "timeline-weekend", report_id: "report-1", detail_report_id: "report-1", report_date: "2026-08-02", market_as_of_date: null, reported_status: "avoid", effective_status: "avoid", has_detailed_assessment: true, path: { ...pathEntry, path_status: "avoid", path_status_label: "不碰" }, market_overlay: { kind: "primary", label: "通信ETF +4.86%", market_date: "2026-07-31", pct_change: 4.86, primary: { name: "通信ETF", security_code: "515880.SH", role: "etf", close: 1.25, pct_change: 4.86, trading_date: "2026-07-31" }, instruments: [] } }] }; mockApi({ sectorResearch: timelineResearch }); renderAt("/sectors/sector-2"); const tile = await screen.findByRole("button", { name: /08-02.*不.*行07-31.*\+4.86%/ }); expect(tile.querySelector(".sector-timeline-market")).toHaveTextContent("行07-31"); });
  it("shows ten completed sector trading days in ascending order with compound return semantics", async () => { renderAt("/sectors/sector-2"); expect(await screen.findByText("最近10个交易日")).toBeInTheDocument(); expect(screen.getByText((_, element) => element?.tagName === "P" && element.textContent?.includes("10日累计：+2.00%") === true)).toBeInTheDocument(); const cells = Array.from(document.querySelectorAll(".recent-five-detail span")); expect(cells).toHaveLength(10); expect(cells[0]).toHaveTextContent("2026-07-20"); expect(cells.at(-1)).toHaveTextContent("2026-07-31"); expect(cells[0]).toHaveClass("up"); expect(cells[1]).toHaveClass("down"); expect(cells[2]).toHaveClass("flat"); expect(document.body).not.toHaveTextContent("2026-07-25"); expect(document.body).not.toHaveTextContent("2026-07-26"); });
  it("reader_hides_empty_official_board_section", async () => { renderAt("/sectors/sector-2"); await screen.findByText("固定主观察 · 最近完整收盘行情"); expect(screen.queryByText("当前官方板块行情")).not.toBeInTheDocument(); });
  it("primary_observation_still_visible", async () => { renderAt("/sectors/sector-2"); expect(await screen.findByText("通信ETF · 515880.SH")).toBeInTheDocument(); expect(screen.getByText("完整交易日：2026-07-31")).toBeInTheDocument(); });
  it("unavailable_sector_still_truthful", async () => { mockApi({ sectorResearch: { ...research, primary_market: null, recent_10_trading_days: [] }, viewerObservation: { market_path_key: "glass_substrate", viewer_source_mode: "unavailable", fallback_reason: "no_reliable_security_proxy", official_board: { available: false, fresh: false }, security_proxy: null, disclosure: "玻璃基板：当前无可靠证券代理，不发起代理行情请求。" } }); renderAt("/sectors/sector-2"); expect(await screen.findByText("暂无可靠代理证券行情；报告观点保持可用。")).toBeInTheDocument(); expect(screen.queryByText("当前官方板块行情")).not.toBeInTheDocument(); });
  it("degrades to the available completed trading days without zero filling", async () => { mockApi({ sectorResearch: { ...research, primary_market: { ...primaryMarket, history_days: 3, history: sectorRecentDays.slice(0, 3), return_10d: null } } }); renderAt("/sectors/sector-2"); expect(await screen.findByText("当前仅有 3 个完整交易日")).toBeInTheDocument(); expect(document.querySelectorAll(".recent-five-detail span")).toHaveLength(3); expect(screen.getByText((_, element) => element?.tagName === "P" && element.textContent?.includes("10日累计：+2.00%") === true)).toBeInTheDocument(); });
  it("exposes readable attribution and license links", () => { renderAt("/about", null); expect(screen.getByRole("heading", { name: "项目与第三方组件说明" })).toBeVisible(); expect(screen.getByRole("link", { name: "查看原项目" })).toHaveAttribute("href", "https://github.com/guokaigdg/animal-island-ui"); expect(screen.getByRole("link", { name: /CC BY-NC 4.0/ })).toHaveAttribute("href", "https://creativecommons.org/licenses/by-nc/4.0/"); });
});

describe("Admin workflow and permissions", () => {
  beforeEach(() => mockApi());
  it("redirects a non-admin away from admin routes", async () => { renderAt("/admin", { username: "viewer", role: "viewer" }); expect(await screen.findByRole("heading", { name: "Admin 登录" })).toBeInTheDocument(); });
  it("allows an unauthenticated visitor to read reports", async () => { renderAt("/reports", null); expect(await screen.findByRole("table", { name: "已发布报告" })).toBeInTheDocument(); });
  it("keeps the Admin entry low-profile but available to anonymous readers", async () => { renderAt("/", null); expect(await screen.findByRole("link", { name: "Admin" })).toHaveAttribute("href", "/admin/login"); });
  it("allows an admin to see the dashboard and its read-only daily status", async () => { renderAt("/admin", { username: "admin", role: "admin" }); expect(await screen.findByRole("heading", { name: "最近两周直播日程" })).toBeInTheDocument(); expect(screen.getByText("每日运行状态")).toBeInTheDocument(); expect(screen.getByText("BUILD_COMMIT")).toBeInTheDocument(); expect(screen.getByText("DATA_SNAPSHOT_DATE")).toBeInTheDocument(); expect(screen.getAllByText("2026-08-11")).toHaveLength(4); });
  it("shows one upload-and-publish action without technical parse buttons", () => { renderAt("/admin/reports/new", { username: "admin", role: "admin" }); expect(screen.getByRole("button", { name: "上传并自动发布" })).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "本地解析" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "增强解析" })).not.toBeInTheDocument(); });
  it("rejects an invalid PDF in the browser", () => { renderAt("/admin/reports/new", { username: "admin", role: "admin" }); const input = document.querySelector('input[type="file"]') as HTMLInputElement; fireEvent.change(input, { target: { files: [new File(["bad"], "bad.txt", { type: "text/plain" })] } }); expect(screen.getByRole("alert")).toHaveTextContent("请选择有效 PDF 文件"); });
  it("previews MD metadata and automatically opens the interpretation result", async () => { mockApi({ duplicate: true }); const user = userEvent.setup(); renderAt("/admin/reports/new", { username: "admin", role: "admin" }); const inputs = Array.from(document.querySelectorAll('input[type="file"]')) as HTMLInputElement[]; await user.upload(inputs[0], new File(["%PDF-fixture"], "fixture.pdf", { type: "application/pdf" })); await user.upload(inputs[1], new File([websiteMdFixture], "fixture.md", { type: "text/markdown" })); expect(await screen.findByText("2026-09-01")).toBeInTheDocument(); expect(screen.getByText("leopard-website-md")).toBeInTheDocument(); expect(screen.getByText("客户端预检通过，等待服务端严格校验")).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "上传并自动发布" })); expect(await screen.findByText("解读完成")).toBeInTheDocument(); expect(await screen.findByRole("heading", { name: report.title })).toBeInTheDocument(); });
  it("renders the three-step review summary and only one primary publish action", async () => { renderAt("/admin/reports/report-1/interpretation", { username: "admin", role: "admin" }); expect(await screen.findByText(report.core_view)).toBeInTheDocument(); expect(screen.getByText(report.market_path)).toBeInTheDocument(); expect(screen.getAllByText("上传报告").length).toBeGreaterThan(0); expect(screen.getByText("自动确认")).toBeInTheDocument(); expect(screen.getByText("建议检查")).toBeInTheDocument(); expect(screen.getByText("必须处理")).toBeInTheDocument(); expect(screen.getAllByRole("button", { name: "确认并发布" })).toHaveLength(1); expect(screen.queryByRole("button", { name: "本地解析" })).not.toBeInTheDocument(); });
  it("shows a semantic upload summary after automatic publication", async () => { const publishedInterpretation: Interpretation = { ...interpretation, ingestion_summary: { publication: "published", report_date: "2026-08-11", template_version: "V2.9", defense_lines: { primary_defense_line: 3878.83, secondary_defense_line: 3864.27 }, history_matrix: { display_rows: 74, active_objects: 71, canonical_rows: 66, new_dates: ["2026-08-11"], inserted_cells: 66, verified_same_cells: 2970, conflicts: 0 }, manual_review: "not_required" }, review_workflow: { ...interpretation.review_workflow, workflow_status: "published" } }; mockApi(); vi.stubGlobal("fetch", vi.fn((input: RequestInfo | URL) => String(input).endsWith("/admin/reports/report-1/interpretation") ? response({ report: { ...report, status: "published" }, interpretation: publishedInterpretation }) : response({ error: { code: "not_found", message: "not found" } }, 404))); renderAt("/admin/reports/report-1/interpretation", { username: "admin", role: "admin" }); expect(await screen.findByText("本次上传结果")).toBeInTheDocument(); expect(screen.getByText("74行 / 71有效")).toBeInTheDocument(); expect(screen.getByText("人工确认：无需确认")).toBeInTheDocument(); });
  it("keeps raw text, all 66 paths and technical controls collapsed", async () => { renderAt("/admin/reports/report-1/interpretation", { username: "admin", role: "admin" }); expect(await screen.findByText("查看全部66个板块路径")).toBeInTheDocument(); expect(screen.getByText("高级技术信息")).toBeInTheDocument(); expect(screen.queryByText("fixture")).not.toBeVisible(); });
});

describe("Accessibility foundations", () => {
  beforeEach(() => mockApi());
  it("shows the single shared ICP registration link in the public shell", async () => {
    renderAt("/");
    const registration = await screen.findByRole("link", { name: "沪ICP备2026042082号-1" });
    expect(screen.getAllByRole("link", { name: "沪ICP备2026042082号-1" })).toHaveLength(1);
    expect(registration).toHaveAttribute("href", "https://beian.miit.gov.cn/");
    expect(registration).toHaveAttribute("target", "_blank");
    expect(registration).toHaveAttribute("rel", "noopener noreferrer");
    expect(document.body).not.toHaveTextContent(["苏", "ICP备2026042082号-1"].join(""));
    expect(screen.getByText("研究型 Web MVP · 报告事实与行情数据分离")).toBeVisible();
  });
  it("supports keyboard focus on the low-priority Admin entry and primary navigation", async () => { const user = userEvent.setup(); renderAt("/"); await user.tab(); expect(document.activeElement).toHaveAttribute("href", "/admin/login"); await user.tab(); expect(document.activeElement).toHaveAttribute("href", "/"); });
  it("uses text and symbols for status, not color alone", async () => { renderAt("/sectors"); expect(await screen.findByText("不支持1项")).toHaveTextContent("不支持1项"); });
  it("declares reduced-motion behavior", () => { const css = readFileSync(resolve(process.cwd(), "src/styles/global.css"), "utf8"); expect(css).toContain("prefers-reduced-motion"); });
  it("keeps narrative copy at normal weight", () => { const css = readFileSync(resolve(process.cwd(), "src/styles/global.css"), "utf8"); expect(css).toMatch(/body\s*\{[^}]*font-weight:\s*400/); expect(css).toMatch(/pdf-assessment-table td:nth-child\(4\)[^}]*font-weight:\s*400/); expect(css).toMatch(/pdf-assessment-table td:nth-child\(5\)[^}]*font-weight:\s*400/); expect(css).toMatch(/\.sector-table\s*\{[^}]*PingFang SC[^}]*font-size:\s*13px/); expect(css).toMatch(/\.sector-table thead th[^}]*font-weight:\s*600[^}]*white-space:\s*nowrap/); expect(css).toMatch(/\.sector-table td[^}]*font-weight:\s*400/); expect(css).toMatch(/\.realtime-cell b[^}]*font-size:\s*14px[^}]*font-weight:\s*600/); });
  it("includes responsive layout rules", () => { const css = readFileSync(resolve(process.cwd(), "src/styles/global.css"), "utf8"); expect(css).toContain("@media (max-width: 760px)"); });
});
